import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/layout/navbar'
import ThemeProvider from '@/components/layout/themeProvider'
import { ClerkProvider } from '@clerk/nextjs'
import Footer from '@/components/layout/footer'
import BottomBar from '@/components/layout/bottomBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <main className="flex min-h-screen flex-col">
            <Navbar/>
            {children}
            <BottomBar/>
            <Footer/>
          </main>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  )
}
