import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { ClerkProvider } from '@clerk/nextjs'
import Footer from '@/components/layout/footer'
import Navbar from '@/components/layout/navbar'
import { Toaster } from '@/components/ui/toaster'
import ThemeProvider from '@/components/layout/themeProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider enableSystem={false} attribute="class">
            <Toaster />
            <main className="flex min-h-screen flex-col bg-white dark:bg-[#101010]">
              <Navbar/>
              {children}
              <Footer/>
            </main>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
